# Generated by Django 4.0.2 on 2022-05-18 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_prueba'),
    ]

    operations = [
        migrations.DeleteModel(
            name='prueba',
        ),
    ]
